# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [2]:
import numpy as np

In [3]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


給定 zeros 會有會有 0 個起始值，但給 empty 有矩陣的形狀，但沒有指定特定的元素值。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [5]:
# 記得先 Import 正確的套件

import numpy as np 

In [8]:
a = np.random.rand(2, 3)
a
a.round() # 直接四捨五入？

array([[0.27963181, 0.69052961, 0.3714051 ],
       [0.53048998, 0.68000359, 0.09800617]])

In [11]:
# 參考解答
a = np.random.rand(2, 3)
a = (a*100).round()
a

array([[98.,  6., 82.],
       [44., 72., 21.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [14]:
m = 20
n = 40

a = np.random.rand(2, 3)
a = (a * (n - m) + m).round()
a

array([[35., 37., 20.],
       [37., 36., 32.]])

思考方向：
1. random.rand 可以設定範圍嗎？ #好像不行
https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html
2. 數學邏輯