In [1]:
import numpy as np

題目:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,55,60])

chinese_score = np.array([65,90,82,72,66,77])


以上3列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文55分、數學60分、國文65分，運用上列數據回答下列問題。

有多少學生英文成績比數學成績高?
是否全班同學最高分都是國文?

In [26]:
#1.有多少學生英文成績比數學成績高?

In [2]:
#2.是否全班同學最高分都是國文?

In [4]:
np.greater(np.array([55,89,76,65,48,70]),np.array([60,85,60,68,55,60]))

array([False,  True,  True, False, False,  True])

In [5]:
# 題1答案為：3個學生

In [ ]:
# 設 a 為國文成績與英文成績之比較；b 為國文成績與數學成績之比較 

In [6]:
a = np.greater(np.array([65,90,82,72,66,77]),np.array([55,89,76,65,48,70]))

In [7]:
b = np.greater(np.array([65,90,82,72,66,77]),np.array([60,85,60,68,55,60]))

In [8]:
a

array([ True,  True,  True,  True,  True,  True])

In [9]:
b

array([ True,  True,  True,  True,  True,  True])

In [10]:
np.logical_and(a,b)

array([ True,  True,  True,  True,  True,  True])

In [ ]:
# a 與 b 做 and，故全班國文成績皆為最高分