# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


list(a) 會只把第一層轉成 list；但 a.tolist() 會把整串轉成一個 list 

array([[1,2,3,4],[5,6,7,8],[9,10,11,12]]) 

list(a) 會變成 [array([1,2,3,4]), array([5,6,7,8]), array([9,10,11,12])]

但 tolist 會整串變成一個 list: [[1,2,3,4],[5,6,7,8],[9,10,11,12]]

### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [2]:
a = np.random.randint(10, size=6) 
a

array([1, 0, 0, 3, 8, 4])

In [3]:
print('幾維：', a.ndim)
print('形狀：', a.shape)
print('元素數量：', a.size)
print('型別：', a.dtype)
print('每個元素佔用的空間：', a.itemsize)
print('長度：', len(a))
print('整個 a 的型別：',type(a) )

幾維： 1
形狀： (6,)
元素數量： 6
型別： int64
每個元素佔用的空間： 8
長度： 6
整個 a 的型別： <class 'numpy.ndarray'>


In [4]:
b = np.random.randint(10, size=(3,4)) 
b
print('幾維：', b.ndim)
print('形狀：', b.shape)
print('元素數量：', b.size)
print('型別：', b.dtype)
print('每個元素佔用的空間：', b.itemsize)
print('長度：', len(b))
print('整個 b 的型別：',type(b) )

幾維： 2
形狀： (3, 4)
元素數量： 12
型別： int64
每個元素佔用的空間： 8
長度： 3
整個 b 的型別： <class 'numpy.ndarray'>


In [5]:
c = np.random.randint(10, size=(2,3,2)) 
c
print('幾維：', c.ndim)
print('形狀：', c.shape)
print('元素數量：', c.size)
print('型別：', c.dtype)
print('每個元素佔用的空間：', c.itemsize)
print('長度：', len(c))
print('整個 c 的型別：',type(c) )

幾維： 3
形狀： (2, 3, 2)
元素數量： 12
型別： int64
每個元素佔用的空間： 8
長度： 2
整個 c 的型別： <class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [6]:
a = np.random.randint(10, size=6) 
a

array([4, 1, 4, 6, 0, 7])

In [10]:
# 一維矩陣 a，兩者無差別
print(list(a))

[1, 0, 0, 3, 8, 4]


In [12]:
print(a.tolist())

[1, 0, 0, 3, 8, 4]


In [13]:
#二維矩陣 b
b = np.random.randint(10, size=(3,4)) 
b

array([[2, 5, 4, 7],
       [8, 7, 3, 9],
       [8, 5, 1, 0]])

In [38]:
type(b)

numpy.ndarray

In [14]:
print(b.tolist())
print(list(b))

[[2, 5, 4, 7], [8, 7, 3, 9], [8, 5, 1, 0]]


In [29]:
#用一個 for 迴圈把 b 一層層轉 list, 再放回新的 list
listed_b = list(b)
new_b = []
for i in listed_b:
    new_b.append(list(i))

In [31]:
new_b

[[2, 5, 4, 7], [8, 7, 3, 9], [8, 5, 1, 0]]

In [37]:
type(listed_b )

list

In [32]:
# 三維矩陣 c
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[3, 2], [6, 5], [3, 1]], [[1, 7], [5, 8], [9, 8]]]
[array([[3, 2],
       [6, 5],
       [3, 1]]), array([[1, 7],
       [5, 8],
       [9, 8]])]


In [34]:
listed_c = list(c)
new_c = []
for i in listed_c:
    new_c.append(list(i))

In [35]:
new_c

[[array([3, 2]), array([6, 5]), array([3, 1])],
 [array([1, 7]), array([5, 8]), array([9, 8])]]

In [57]:
type(listed_c[1])

numpy.ndarray

In [61]:
def tolist(iterable):
    if type(iterable) != np.ndarray:
        return iterable
    new_list = []
    for i in iterable:
        new_list.append(tolist(i))
    return new_list

print(tolist(a))
print(tolist(b))
# print(tolist(c))

[1, 0, 0, 3, 8, 4]
[[2, 5, 4, 7], [8, 7, 3, 9], [8, 5, 1, 0]]


觀察不同層的 type，一個個元素提出來看他的型別做成迴圈

list 會常常遇到的問題：list is not callable

解決問題

(1) (( )) 改成 ([ ])

(2) 可能有重複命名到 -> 這次就是原本的第一個我只用註解掉沒有用 markdown