In [1]:
import numpy as np

array1 = np.array([[10, 8], [3, 5]])



運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
運用上列array計算特徵值、特徵向量?
運用上列array計算SVD?

In [2]:
array1 = np.array([[10, 8], [3, 5]])

In [6]:
array2 = np.linalg.inv(array1) #array1 的反矩陣

In [7]:
array2

array([[ 0.19230769, -0.30769231],
       [-0.11538462,  0.38461538]])

In [8]:
np.dot(array1, array2) # 為單位矩陣

array([[1., 0.],
       [0., 1.]])

In [9]:
w, v = np.linalg.eig(array1)

In [10]:
w #特徵值

array([13.,  2.])

In [11]:
v #特徵向量

array([[ 0.93632918, -0.70710678],
       [ 0.35112344,  0.70710678]])

In [12]:
u, s, vh = np.linalg.svd(array1) #計算 svd

In [13]:
u

array([[-0.91663818, -0.39971796],
       [-0.39971796,  0.91663818]])

In [14]:
s

array([13.94721714,  1.86417116])

In [15]:
vh

array([[-0.74319741, -0.6690722 ],
       [-0.6690722 ,  0.74319741]])