In [2]:
!pip3 install numpy

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun


In [4]:
np.__version__

NameError: name 'np' is not defined

In [5]:
import numpy as np

In [6]:
np.__version__

'1.18.1'

In [7]:
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。

In [9]:
a = np.arange(21)

In [10]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
#2.呈上題，將以上數列取出偶數。

In [12]:
a[0::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
#3.呈1題，將數列取出3的倍數。

In [15]:
a[3::3]

array([ 3,  6,  9, 12, 15, 18])