In [6]:
!pip3 install numpy

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun


In [4]:
np.__version__

'1.18.1'

In [26]:
array1 = np.array(range(30))

In [28]:
#將上列陣列(array1)，轉成維度為(5X6)的 array，順序按列填充。(hint:order="F")

In [29]:
array1.resize((5,6),refcheck = False)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [30]:
array1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
#呈上題的 array，找出被 6 除餘 1 的數的索引

In [43]:
np.where(array1 % 6 == 1)

(array([0, 1, 2, 3, 4]), array([1, 1, 1, 1, 1]))